const institutionsData = [
    {
      id: '0',
      name: 'University of Michigan',
      img: 'https://unsplash.it/400/100',
      production: 'Edgar Allan Poe',
      artist: 'Cheryl Warren, Rocco D Dowd',
      status: 'active',
      email: 'universityMi@example.com',
      website: 'https://www.umich.edu/',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
    {
      id: '1',
      name: 'Carnegie Mellon ',
      img: 'https://unsplash.it/400/800',
      production: 'The Great Gatsby',
      artist: 'Randall Carrion',
      status: 'active',
      email: 'carnegie@mellon.com',
      website: 'carnegie-mellon.com',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
    {
      id: '2',
      name: 'Guildhall',
      img: 'https://unsplash.it/400/300',
      production: 'Wicked',
      artist: 'Ruth Davis',
      status: 'active',
      email: 'guidhallinstitution@mail.com',
      website: 'www.guidhall.com',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
    {
      id: '3',
      name: 'Curtis Institute of Music',
      img: 'https://unsplash.it/400/200',
      production: 'Bones',
      artist: 'Charles McDermott',
      status: 'active',
      email: 'curtisinstitution@music.com',
      website: 'www.curtisinstitution.com',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
    {
      id: '4',
      name: 'The Juilliard School',
      img: 'https://unsplash.it/400/500',
      production: 'Lucky',
      artist: 'Raymond Clark',
      status: 'active',
      email: 'juilliard@mail.com',
      website: 'www.juilliard.com',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
    {
      id: '5',
      name: 'Mannes School',
      img: 'https://unsplash.it/400/200',
      production: 'Dawn of the Dead, Lethal Weapon, Silent Hill',
      artist: 'Ray Elliott',
      status: 'active',
      email: 'manneseduction@mail.com',
      website: 'www.mannes.edu',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
    {
      id: '6',
      name: 'Golden Hill Music',
      img: 'https://unsplash.it/400/600',
      production: 'Nancy',
      artist: 'Michael Miller',
      status: 'active',
      email: 'goldenhill@music.com',
      website: 'www.goldenhillmusic.com',
      date_joined: '03/12/2012',
      productions_count: 24,
      artists_count: 13000,
      search_count: 4567,
      role: 'Admin-artists',
      productions: [
        {
          id: '0',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Hall of Fame',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'New York, NY',
        },
        {
          id: '1',
          name: 'Dawn of the Dead',
          img: 'https://unsplash.it/400/200',
          performances: 'The Great Hall',
          start_end_date: '04/04/2010 - 04/04/2011',
          location: 'San Francisco, CA',
        },
        {
          id: '2',
          name: 'Silent Hill',
          img: 'https://unsplash.it/400/200',
          performances: 'Broadway',
          start_end_date: '05/09/2017 - 10/26/2018',
          location: 'Chicago, IL',
        },
        {
          id: '3',
          name: 'The Royal Academy of Music',
          img: 'https://unsplash.it/400/200',
          performances: 'Dance Hall',
          start_end_date: '10/09/2017 - 10/26/2018',
          location: 'New York, NY',
        },
        {
          id: '4',
          name: 'Lethal Weapon',
          img: 'https://unsplash.it/400/200',
          performances: 'Walt Disney Concert Hall',
          start_end_date: '02/02/2009 - 02/02/2010',
          location: 'Miami, FL',
        },
        {
          id: '5',
          name: 'The Last of the Mohicans',
          img: 'https://unsplash.it/400/200',
          performances: 'Festival Hall',
          start_end_date: '05/05/2011 - 05/05/2012',
          location: 'Jackson, MS',
        },
      ],
      institutions: [
        {
          id: '0',
          name: 'University of California, Berkeley',
          type: 'User',
          role: 'B.A. in Art History',
        },
        {
          id: '1',
          name: 'Duke University',
          type: 'User',
          role: 'M.S. in Music',
        },
        {
          id: '2',
          name: 'Florida State University',
          type: 'User',
          role: 'Research Assistant',
        },
        {
          id: '3',
          name: 'Kettering University',
          type: 'User',
          role: 'Academic Advisor',
        },
        {
          id: '4',
          name: 'Stanford University',
          type: 'User',
          role: 'Lecturer',
        },
        {
          id: '5',
          name: 'Emory University',
          type: 'User',
          role: 'Faculty Advisor',
        },
      ],
      artists: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '06/06/2016',
        },
        {
          id: '1',
          name: 'Cody Fisher',
          img: 'https://unsplash.it/400/200',
          email: 'cody.fisher@example.com',
          type: 'User',
          role: 'Artist',
          date_joined: '04/17/2009',
        },
        {
          id: '2',
          name: 'Esther Howard',
          img: 'https://unsplash.it/400/200',
          email: 'esther.howard@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '08/01/2014',
        },
        {
          id: '3',
          name: 'Jenny Wilson',
          img: 'https://unsplash.it/400/200',
          email: 'jenny.wilson@example.com',
          type: 'User',
          role: 'Member',
          date_joined: '05/01/2015',
        },
        {
          id: '4',
          name: 'Kristin Watson',
          img: 'https://unsplash.it/400/200',
          email: 'kristin.watson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '02/01/2016',
        },
        {
          id: '5',
          name: 'Cameron Williamson',
          img: 'https://unsplash.it/400/200',
          email: 'cameron.williamson@example.com',
          type: 'User',
          role: 'Producer',
          date_joined: '11/19/2018',
        },
      ],
      admin: [
        {
          id: '0',
          name: 'Jane Cooper',
          img: 'https://unsplash.it/400/200',
          email: 'jane.cooper@example.com',
          status: 'active',
        },
      ],
      banking: [
        {
          information: [
            {
              institution_owner: '-----------',
              institution_address: '-----------',
              institution_account_number: '-----------',
              institution_routing_number: '-----------',
            },
          ],
          payoutHistory: [
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
            {
              transaction: '-----------',
              date: '-----------',
              amount: '-----------',
            },
          ],
        },
      ],
      profile: [
        {
          title: 'Venues',
          rows: [
            {
              name: 'Carnegie Hall',
              address: '123 Main St',
              seating_capacity: '7567',
              completion_date: '11/19/2018',
              stageConfiguration: '4x4',
              specialFeatures: 'Lights, sound, and stage',
              photo:
                'https://www.pqc.edu/wp-content/uploads/revslider/slider3/greybox.png',
              description:
                'The Carnegie Hall is a historic landmark in the Theater District of Pittsburgh, Pennsylvania, United States. It is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh. The Carnegie Hall is the oldest performing arts complex in the United States, and the second oldest in the world. It is located in the heart of Pittsburgh, on the banks of the Ohio River, adjacent to the University of Pittsburgh.',
            },
          ],
        },
      ],
    },
  ];
  /*id*	number
uuid*	string
type*	string
name*	string
street	string
city	string
state	string
zipcode	string
latitude	number
longitude	number
website	string
resourceLocation	string
createdAt*	string($date-time)
updatedAt*	string($date-time)
programs	[...]
productions	[...]
featuredProductions*	[...]
featuredArtistContributions*	[...]
}*/
/* heres all the possible institutionTypes: 

  secondarySchool = 'SECONDARY SCHOOL',
  university = 'UNIVERSITY',
  communityTheaterAdult = 'COMMUNITY THEATER ADULT',
  communityTheaterYouth = 'COMMUNITY THEATER YOUTH',
  regionalTheater = 'REGIONAL THEATER'
  
  programs:

  programs	[InstitutionProgram{
id*	number
uuid*	string
institutionId*	number
name*	string
artistHeadId	number
website	string
createdAt*	string($date-time)
updatedAt*	string($date-time)
institution*	{...}
artistHead*	Artist{...}
featuredProductions*	[...]
featuredArtistContributions*	[...]
}]
  
  
  */
 
//copilot help me rewrite institutionsData to fit match the above parameters and make random

const copilotInstitutionsData = [
    {
        id: '0',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'University of Michigan',
        img: 'https://unsplash.it/400/100',
        type: 'COMMUNITY_THEATER_YOUTH',
        street: '651 S. State St.',
        city: 'Ann Arbor',
        state: 'MI',
        zipcode: '48109',
        latitude: '42.2700',
        longitude: '-83.7000',
        website: 'https://www.umich.edu/',
        resourceLocation: 'https://www.umich.edu/',
        createdAt: '2018-11-19T00:00:00.000Z',
        updatedAt: '2018-11-19T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    },
    {
        id: '1',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'Guildhall',
        img : 'https://unsplash.it/400/200',
        type: 'REGIONAL_THEATER',
        street: '3245 96th St.',
        city: 'Pittsburgh',
        state: 'PA',
        zipcode: '15213',
        latitude: '40.2700',
        longitude: '-83.7000',
        website: 'https://www.guildhall.org/',
        resourceLocation: 'https://www.guildhall.org/',
        createdAt: '2018-11-19T00:00:00.000Z',
        updatedAt: '2018-11-19T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    },
    {
        id: '2',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'Carnegie Hall',
        img: 'https://unsplash.it/100/200',
        type: 'COMMUNITY_THEATER_ADULT',
        street: '1901 S. State St.',
        city: 'Pittsburgh',
        state: 'PA',
        zipcode: '15213',
        latitude: '40.2700',
        longitude: '-83.7000',
        website: 'https://www.carnegiehall.org/',
        resourceLocation: 'https://www.carnegiehall.org/',
        createdAt: '2018-10-29T00:00:00.000Z',
        updatedAt: '2018-10-29T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    },
    {
        id: '3',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'Theater District',
        img: 'https://unsplash.it/400/500',
        type: 'SECONDARY_SCHOOL',
        street: '123 Main St.',
        city: 'Chicago',
        state: 'IL',
        zipcode: '48109',
        latitude: '42.2700',
        longitude: '-83.7000',
        website: 'https://www.theaterdistrict.org/',
        resourceLocation: 'https://www.theaterdistrict.org/',
        createdAt: '2018-10-29T00:00:00.000Z',
        updatedAt: '2018-10-29T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    },
    {
        id: '4',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'The Art Institute of Chicago',
        img: 'https://unsplash.it/400/400',
        type: 'UNIVERSITY',
        street: '123 Main St.',
        city: 'Chicago',
        state: 'IL',
        zipcode: '48109',
        latitude: '42.2700',
        longitude: '-83.7000',
        website: 'https://www.artic.edu/',
        resourceLocation: 'https://www.artic.edu/',
        createdAt: '2018-10-29T00:00:00.000Z',
        updatedAt: '2018-10-29T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    },
    {
        id: '5',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'The Juilliard School',
        img: 'https://unsplash.it/200/100',
        type: 'UNIVERSITY',
        street: '123 Main St.',
        city: 'New York',
        state: 'NY',
        zipcode: '48109',
        latitude: '42.2700',
        longitude: '-83.7000',
        website: 'https://www.juilliard.edu/',
        resourceLocation: 'https://www.juilliard.edu/',
        createdAt: '2018-10-29T00:00:00.000Z',
        updatedAt: '2018-10-29T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    },
    {
        id: '6',
        uuid: "3f8a9f8a-9f8a-9f8a-9f8a-9f8a9j8a9f8a",
        name: 'The Juilliard School',
        img: 'https://unsplash.it/100/100',
        type: 'UNIVERSITY',
        street: '123 Main St.',
        city: 'New York',
        state: 'NY',
        zipcode: '48109',
        latitude: '42.2700',
        longitude: '-83.7000',
        website: 'https://www.juilliard.edu/',
        resourceLocation: 'https://www.juilliard.edu/',
        createdAt: '2018-10-29T00:00:00.000Z',
        updatedAt: '2018-10-29T00:00:00.000Z',
        programs: [''],
        productions: [''],
        featuredProductions: [''],
        featuredArtistContributions: [''],
    }
];